// Canonical financial templates extracted from Base_Cálculo_Indicadores.xlsx
// These define the standard structure for BP (55 lines), DRE (25 lines), and 36 indicators

export const BP_TEMPLATE: Array<{ classificacao: string; conta: string; nivel: number }> = [
  // ATIVO
  { classificacao: "AT", conta: "Ativo Total", nivel: 0 },
  { classificacao: "AC", conta: "Ativo Circulante", nivel: 1 },
  { classificacao: "AF", conta: "Caixa e Equivalentes de Caixa", nivel: 2 },
  { classificacao: "AO", conta: "Contas a Receber", nivel: 2 },
  { classificacao: "AO", conta: "Estoques", nivel: 2 },
  { classificacao: "AO", conta: "Ativos Biológicos", nivel: 2 },
  { classificacao: "AO", conta: "Tributos a Recuperar", nivel: 2 },
  { classificacao: "AF", conta: "Outros Créditos a Receber", nivel: 2 },
  { classificacao: "AO", conta: "Despesas Ant. / Adiantamentos - Ativo", nivel: 2 },
  { classificacao: "AF", conta: "Outros Ativos Circulantes", nivel: 2 },
  { classificacao: "ANC", conta: "Ativo Não Circulante", nivel: 1 },
  { classificacao: "ANC", conta: "Realizável a Longo Prazo", nivel: 2 },
  { classificacao: "ANC", conta: "Investimentos", nivel: 2 },
  { classificacao: "ANC", conta: "Imobilizado", nivel: 2 },
  { classificacao: "ANC", conta: "Intangível", nivel: 2 },
  { classificacao: "ANC", conta: "Bens a Alienar", nivel: 2 },
  { classificacao: "ANC", conta: "Ativo Diferido", nivel: 2 },

  // PASSIVO
  { classificacao: "PT", conta: "Passivo Total", nivel: 0 },
  { classificacao: "PC", conta: "Passivo Circulante", nivel: 1 },
  { classificacao: "PO", conta: "Fornecedores", nivel: 2 },
  { classificacao: "PO", conta: "Obrigações Trabalhistas", nivel: 2 },
  { classificacao: "PO", conta: "Obrigações Tributárias", nivel: 2 },
  { classificacao: "PF", conta: "Empréstimos e Financiamentos - Curto Prazo", nivel: 2 },
  { classificacao: "PF", conta: "Passivos com Partes Relacionadas - Curto Prazo", nivel: 2 },
  { classificacao: "PF", conta: "Dividendos e JCP a Pagar", nivel: 2 },
  { classificacao: "PF", conta: "Despesas Ant. / Adiantamentos - Passivo", nivel: 2 },
  { classificacao: "PF", conta: "Outros Passivos Circulantes", nivel: 2 },
  { classificacao: "PNC", conta: "Passivo Não Circulante", nivel: 1 },
  { classificacao: "PNC", conta: "Empréstimos e Financiamentos - Longo Prazo", nivel: 2 },
  { classificacao: "PNC", conta: "Passivos com Partes Relacionadas - Longo Prazo", nivel: 2 },
  { classificacao: "PNC", conta: "Tributos Diferidos - Longo Prazo", nivel: 2 },
  { classificacao: "PNC", conta: "Adiantamento para Futuro Aumento Capital - Longo Prazo", nivel: 2 },
  { classificacao: "PNC", conta: "Participação nos Lucros ou Resultados", nivel: 2 },
  { classificacao: "PNC", conta: "Dividendos e Juros sobre o Capital Próprio", nivel: 2 },

  // PATRIMÔNIO LÍQUIDO
  { classificacao: "PL", conta: "Patrimônio Líquido", nivel: 1 },
  { classificacao: "PL", conta: "Capital Social", nivel: 2 },
  { classificacao: "PL", conta: "Reservas de Capital", nivel: 2 },
  { classificacao: "PL", conta: "Reservas de Reavaliação", nivel: 2 },
  { classificacao: "PL", conta: "Reservas de Lucros", nivel: 2 },
  { classificacao: "PL", conta: "Lucros/Prejuízos Acumulados", nivel: 2 },
  { classificacao: "PL", conta: "Resultado do Exercício", nivel: 2 },
  { classificacao: "PL", conta: "Ajustes de Avaliação Patrimonial", nivel: 2 },
  { classificacao: "PL", conta: "Adiantamento para Futuro Aumento Capital - PL", nivel: 2 },
];

// DRE padrão (modelo gerencial Quantua — espelha Modelo_DRE.xlsx).
// Convenção de sinais (alinhada ao restante do sistema): receitas positivas,
// deduções/custos/despesas/IR negativos. Subtotais são calculados em cascata
// por `recomputeDRESubtotals` (account-mapper.ts):
//   Receita Líquida          = Receita Bruta + Deduções + Impostos s/ Faturamento
//   Lucro Bruto              = Receita Líquida + Custo Operacional
//   EBITDA                   = Lucro Bruto + G&A + Vendas + Marketing + P&D + Outras Rec/Desp Op
//   EBIT                     = EBITDA + Depreciação e Amortização + Equivalência Patrimonial
//   Resultado Financeiro     = Receitas Financeiras + Despesas Financeiras
//   Resultado Não Operacional= Outras Receitas Não Op + Outras Despesas Não Op
//   Resultado Antes do IR    = EBIT + Resultado Financeiro + Resultado Não Operacional
//   Lucro Líquido            = Resultado Antes do IR e CSLL + IR e CSLL
export const DRE_TEMPLATE: Array<{ conta: string; subtotal: boolean }> = [
  { conta: "Receita Bruta", subtotal: false },
  { conta: "Deduções da Receita Bruta", subtotal: false },
  { conta: "Impostos s/ Faturamento", subtotal: false },
  { conta: "Receita Líquida", subtotal: true },
  { conta: "Custo Operacional", subtotal: false },
  { conta: "Lucro Bruto", subtotal: true },
  { conta: "Despesas Gerais e Administrativas", subtotal: false },
  { conta: "Despesas com Vendas", subtotal: false },
  { conta: "Despesas com Marketing", subtotal: false },
  { conta: "Despesas com P&D", subtotal: false },
  { conta: "Outras Receitas Operacionais", subtotal: false },
  { conta: "Outras Despesas Operacionais", subtotal: false },
  { conta: "EBITDA", subtotal: true },
  { conta: "Depreciação e Amortização", subtotal: false },
  { conta: "Equivalência Patrimonial", subtotal: false },
  { conta: "EBIT", subtotal: true },
  { conta: "Resultado Financeiro", subtotal: true },
  { conta: "Receitas Financeiras", subtotal: false },
  { conta: "Despesas Financeiras", subtotal: false },
  { conta: "Resultado Não Operacional", subtotal: true },
  { conta: "Outras Receitas Não Operacionais", subtotal: false },
  { conta: "Outras Despesas Não Operacionais", subtotal: false },
  { conta: "Resultado Antes do IR e CSLL", subtotal: true },
  { conta: "IR e CSLL", subtotal: false },
  { conta: "Lucro Líquido", subtotal: true },
];

export const INDICADORES_TEMPLATE: Array<{
  tipo: string;
  nome: string;
  formula: string;
  tipoDado: "R$" | "%" | "Índice" | "Dias" | "Texto";
}> = [
  // Indicadores Operacionais
  { tipo: "Indicadores Operacionais", nome: "Receita Líquida", formula: "Receita Bruta (-) Impostos (-) Cancelamentos", tipoDado: "R$" },
  { tipo: "Indicadores Operacionais", nome: "Lucro Bruto", formula: "Receita Líquida (-) Custo Operacional", tipoDado: "R$" },
  { tipo: "Indicadores Operacionais", nome: "Lucro Operacional", formula: "EBIT = EBITDA (-) Depreciação e Amortização (+) Equivalência Patrimonial", tipoDado: "R$" },
  { tipo: "Indicadores Operacionais", nome: "Lucro Líquido", formula: "Resultado Antes do IR e CSLL (-) IR e CSLL", tipoDado: "R$" },
  { tipo: "Indicadores Operacionais", nome: "NOPAT", formula: "EBIT × (1 - Impostos (34%))", tipoDado: "R$" },

  // Indicadores de Margens
  { tipo: "Indicadores de Margens", nome: "Margem Bruta", formula: "Lucro Bruto / Receita Líquida", tipoDado: "%" },
  { tipo: "Indicadores de Margens", nome: "Margem Operacional", formula: "EBITDA / Receita Líquida", tipoDado: "%" },
  { tipo: "Indicadores de Margens", nome: "Margem Líquida", formula: "Lucro Líquido / Receita Líquida", tipoDado: "%" },

  // Indicadores de Liquidez
  { tipo: "Indicadores de Liquidez", nome: "Liquidez Imediata", formula: "Caixa e Equivalentes de Caixa / Passivo Circulante", tipoDado: "Índice" },
  { tipo: "Indicadores de Liquidez", nome: "Liquidez Seca", formula: "(Ativo Circulante - Estoques) / Passivo Circulante", tipoDado: "Índice" },
  { tipo: "Indicadores de Liquidez", nome: "Liquidez Corrente", formula: "Ativo Circulante / Passivo Circulante", tipoDado: "Índice" },
  { tipo: "Indicadores de Liquidez", nome: "Liquidez Geral", formula: "(Ativo Circulante + Ativo Realizável a Longo Prazo) / (Passivo Circulante + Passivo Não Circulante)", tipoDado: "Índice" },

  // Indicadores de Capital de Giro
  { tipo: "Indicadores de Capital de Giro", nome: "Capital de Giro (CDG)", formula: "Ativo Circulante - Passivo Circulante", tipoDado: "R$" },
  { tipo: "Indicadores de Capital de Giro", nome: "Necessidade de Capital de Giro (NCG)", formula: "Ativo Operacional - Passivo Operacional", tipoDado: "R$" },
  { tipo: "Indicadores de Capital de Giro", nome: "Saldo em Tesouraria (ST)", formula: "Capital de Giro (CDG) - Necessidade de Capital de Giro (NCG)", tipoDado: "R$" },
  { tipo: "Indicadores de Capital de Giro", nome: "Situação da empresa", formula: "Classificação baseada em CDG, NCG e ST", tipoDado: "Texto" },
  { tipo: "Indicadores de Capital de Giro", nome: "Prazo Médio Contas a Receber", formula: "(Contas a Receber × 365) / Receita Líquida", tipoDado: "Dias" },
  { tipo: "Indicadores de Capital de Giro", nome: "Prazo Médio Estoque", formula: "(Estoques × 365) / Custo Operacional", tipoDado: "Dias" },
  { tipo: "Indicadores de Capital de Giro", nome: "Prazo Médio Fornecedores", formula: "(Fornecedores × 365) / Custo Operacional", tipoDado: "Dias" },
  { tipo: "Indicadores de Capital de Giro", nome: "Ciclo Financeiro", formula: "Prazo Médio Contas a Receber + Prazo Médio Estoque - Prazo Médio Fornecedores", tipoDado: "Dias" },

  // Indicadores de Endividamento
  { tipo: "Indicadores de Endividamento", nome: "Caixa e Equivalentes", formula: "Caixa e Equivalentes de Caixa", tipoDado: "R$" },
  { tipo: "Indicadores de Endividamento", nome: "Capital de Terceiros", formula: "Empréstimos e Financiamentos - Curto Prazo + Passivos com Partes Relacionadas - Curto Prazo + Empréstimos e Financiamentos - Longo Prazo + Passivos com Partes Relacionadas - Longo Prazo", tipoDado: "R$" },
  { tipo: "Indicadores de Endividamento", nome: "Dívida Líquida", formula: "Capital de Terceiros - Caixa e Equivalentes", tipoDado: "R$" },
  { tipo: "Indicadores de Endividamento", nome: "Endividamento Geral", formula: "(Passivo Total - Patrimônio Líquido) / Passivo Total", tipoDado: "%" },
  { tipo: "Indicadores de Endividamento", nome: "Endividamento de Curto Prazo", formula: "Passivo Circulante / Passivo Total", tipoDado: "%" },
  { tipo: "Indicadores de Endividamento", nome: "Patrimônio Líquido", formula: "Patrimônio Líquido", tipoDado: "R$" },
  { tipo: "Indicadores de Endividamento", nome: "Capital Terceiros s/ PL", formula: "Capital de Terceiros / Patrimônio Líquido", tipoDado: "Índice" },
  { tipo: "Indicadores de Endividamento", nome: "Dívida Líquida/Lucro Operacional", formula: "Dívida Líquida / EBITDA", tipoDado: "Índice" },
  { tipo: "Indicadores de Endividamento", nome: "Índice de Cobertura de Juros", formula: "EBITDA / Despesas Financeiras", tipoDado: "Índice" },
  { tipo: "Indicadores de Endividamento", nome: "Despesa Financeira / Rec. Líquida", formula: "Despesas Financeiras / Receita Líquida", tipoDado: "%" },

  // Indicadores de Rentabilidade
  { tipo: "Indicadores de Rentabilidade", nome: "ROA (Retorno sobre Ativos)", formula: "Lucro Líquido / Ativo Total", tipoDado: "%" },
  { tipo: "Indicadores de Rentabilidade", nome: "ROIC (Retorno sobre Capital Investido)", formula: "NOPAT / (Patrimônio Líquido + Capital de Terceiros)", tipoDado: "%" },

  // Indicadores de Rentabilidade - Modelo Dupont
  { tipo: "Indicadores de Rentabilidade - Modelo Dupont", nome: "ROE (Retorno sobre Patrimônio Líquido)", formula: "Lucro Líquido / Patrimônio Líquido", tipoDado: "%" },
  { tipo: "Indicadores de Rentabilidade - Modelo Dupont", nome: "Margem Líquida", formula: "Lucro Líquido / Receita Líquida", tipoDado: "%" },
  { tipo: "Indicadores de Rentabilidade - Modelo Dupont", nome: "Giro do Ativo", formula: "Receita Líquida / Ativo Total", tipoDado: "Índice" },
  { tipo: "Indicadores de Rentabilidade - Modelo Dupont", nome: "Alavancagem", formula: "Passivo Total / Patrimônio Líquido", tipoDado: "Índice" },
];

// Account name aliases for normalization
// Maps common variations to the canonical name
export const ACCOUNT_ALIASES: Record<string, string> = {
  // === ATIVO TOTAL ===
  "Total do Ativo": "Ativo Total",
  "Total Geral do Ativo": "Ativo Total",
  "ATIVO": "Ativo Total",
  "A T I V O": "Ativo Total",
  "ATIVO TOTAL": "Ativo Total",
  "TOTAL DO ATIVO": "Ativo Total",
  "Total Ativo": "Ativo Total",
  "SOMA DO ATIVO": "Ativo Total",
  "TOTAL DOS ATIVOS": "Ativo Total",
  "TOTAL GERAL DO ATIVO": "Ativo Total",

  // === ATIVO CIRCULANTE ===
  "Circulante": "Ativo Circulante",
  "Ativo Circulante Total": "Ativo Circulante",
  "Total do Ativo Circulante": "Ativo Circulante",
  "ATIVO CIRCULANTE": "Ativo Circulante",
  "Ativo Circulante Liquido": "Ativo Circulante",
  "TOTAL ATIVO CIRCULANTE": "Ativo Circulante",
  "TOTAL DO ATIVO CIRCULANTE": "Ativo Circulante",

  // === CAIXA E EQUIVALENTES ===
  "Disponibilidades": "Caixa e Equivalentes de Caixa",
  "Disponibilidade": "Caixa e Equivalentes de Caixa",
  "Disponivel": "Caixa e Equivalentes de Caixa",
  "Disponível": "Caixa e Equivalentes de Caixa",
  "Caixa e Bancos": "Caixa e Equivalentes de Caixa",
  "Caixa": "Caixa e Equivalentes de Caixa",
  "CAIXA": "Caixa e Equivalentes de Caixa",
  "Caixa Matriz": "Caixa e Equivalentes de Caixa",
  "CAIXA MATRIZ": "Caixa e Equivalentes de Caixa",
  "Bancos c/ Movimento": "Caixa e Equivalentes de Caixa",
  "BANCOS C/ MOVIMENTO": "Caixa e Equivalentes de Caixa",
  "Contas Bancárias": "Caixa e Equivalentes de Caixa",
  "Depósitos Bancários": "Caixa e Equivalentes de Caixa",
  "Banco Caixa Economica Federal": "Caixa e Equivalentes de Caixa",
  "Banco Conta Movimento": "Caixa e Equivalentes de Caixa",
  "BANCO CONTA MOVIMENTO": "Caixa e Equivalentes de Caixa",
  "Banco do Brasil S/A": "Caixa e Equivalentes de Caixa",
  "Banco Itau S/A": "Caixa e Equivalentes de Caixa",
  "Cheques em Cobrança": "Caixa e Equivalentes de Caixa",
  "CHEQUES EM COBRANÇA": "Caixa e Equivalentes de Caixa",
  "Bancos": "Caixa e Equivalentes de Caixa",
  "Bradesco Ag.0049 C/C 0329707-1": "Caixa e Equivalentes de Caixa",
  "Caixa Economica Federal": "Caixa e Equivalentes de Caixa",
  "Aplicação Bradesco Cdb": "Caixa e Equivalentes de Caixa",
  "Aplicacao Bradesco Fic Fi Rf": "Caixa e Equivalentes de Caixa",
  "Aplicação C.E.F": "Caixa e Equivalentes de Caixa",
  "Fundo de Aplicação Financeira": "Caixa e Equivalentes de Caixa",
  "Aplicações de Liquidez Imediata": "Caixa e Equivalentes de Caixa",
  "APLICAÇÃO DE LIQUIDEZ IMEDIATA": "Caixa e Equivalentes de Caixa",
  "Investimentos Financeiros de Curto Prazo": "Caixa e Equivalentes de Caixa",
  "Aplicação de Liquidez Imediata": "Caixa e Equivalentes de Caixa",
  "Banco Conta Aplicação": "Caixa e Equivalentes de Caixa",
  "BANCO CONTA APLICAÇÃO": "Caixa e Equivalentes de Caixa",
  "Ativos Financeiros": "Caixa e Equivalentes de Caixa",
  "Aplicações Financeiras": "Caixa e Equivalentes de Caixa",
  "APLICAÇÕES FINANCEIRAS": "Caixa e Equivalentes de Caixa",
  "Instrumentos Financeiros": "Caixa e Equivalentes de Caixa",
  "Outros Investimentos Líquido": "Caixa e Equivalentes de Caixa",
  "CAIXA GERAL": "Caixa e Equivalentes de Caixa",
  "CAIXA FILIAL": "Caixa e Equivalentes de Caixa",
  "BANCOS CONTA CORRENTE": "Caixa e Equivalentes de Caixa",
  "BANCO DO BRASIL": "Caixa e Equivalentes de Caixa",
  "BANCO BRADESCO": "Caixa e Equivalentes de Caixa",
  "BANCO ITAU": "Caixa e Equivalentes de Caixa",
  "BANCO SANTANDER": "Caixa e Equivalentes de Caixa",
  "BANCO INTER": "Caixa e Equivalentes de Caixa",
  "BANCO SICOOB": "Caixa e Equivalentes de Caixa",
  "BANCO SICREDI": "Caixa e Equivalentes de Caixa",
  "NUMERARIO EM CAIXA": "Caixa e Equivalentes de Caixa",
  "POUPANÇA": "Caixa e Equivalentes de Caixa",
  "CDB": "Caixa e Equivalentes de Caixa",
  "LCI": "Caixa e Equivalentes de Caixa",
  "LCA": "Caixa e Equivalentes de Caixa",

  // === CONTAS A RECEBER ===
  "Créditos a Receber": "Contas a Receber",
  "Contas a Receber de Clientes": "Contas a Receber",
  "Duplicatas a Receber": "Contas a Receber",
  "DUPLICATAS A RECEBER": "Contas a Receber",
  "Creditos A Receber": "Contas a Receber",
  "Clientes A Receber": "Contas a Receber",
  "CLIENTES A RECEBER": "Contas a Receber",
  "Faturas a Receber Líquidas": "Contas a Receber",
  "Creditos": "Contas a Receber",
  "CREDITOS": "Contas a Receber",
  "Contas a Receber": "Contas a Receber",
  "CONTAS A RECEBER": "Contas a Receber",
  "Clientes": "Contas a Receber",
  "CLIENTES": "Contas a Receber",
  "TITULOS A RECEBER": "Contas a Receber",
  "VALORES A RECEBER": "Contas a Receber",
  "RECEBIVEIS": "Contas a Receber",

  // === ESTOQUES ===
  "Estoques - Almoxarifado": "Estoques",
  "Inventário": "Estoques",
  "Estoque Geral": "Estoques",
  "ESTOQUES": "Estoques",
  "ESTOQUE GERAL": "Estoques",
  "Mercadorias": "Estoques",
  "Produtos Acabados": "Estoques",
  "Matérias-Primas": "Estoques",
  "Estoque": "Estoques",
  "ESTOQUE DE MERCADORIAS": "Estoques",
  "MERCADORIAS PARA REVENDA": "Estoques",
  "ALMOXARIFADO": "Estoques",

  // === ATIVOS BIOLÓGICOS ===
  "Ativos Biológicos": "Ativos Biológicos",

  // === TRIBUTOS A RECUPERAR ===
  "Créditos Tributários": "Tributos a Recuperar",
  "Impostos a Recuperar": "Tributos a Recuperar",
  "IMPOSTOS A RECUPERAR": "Tributos a Recuperar",
  "Tributos a Compensar": "Tributos a Recuperar",
  "Pis A Compensar": "Tributos a Recuperar",
  "Cofins A Compensar": "Tributos a Recuperar",
  "Imposto Pago Em Duplic": "Tributos a Recuperar",
  "Irrf A Compensar": "Tributos a Recuperar",
  "Saldo Negativo Csll": "Tributos a Recuperar",
  "Saldo Negativo Irpj": "Tributos a Recuperar",
  "ICMS a Recuperar": "Tributos a Recuperar",
  "PIS a Recuperar": "Tributos a Recuperar",
  "COFINS a Recuperar": "Tributos a Recuperar",
  "IPI A RECUPERAR": "Tributos a Recuperar",
  "IRPJ A RECUPERAR": "Tributos a Recuperar",
  "CSLL A RECUPERAR": "Tributos a Recuperar",
  "IRRF A RECUPERAR": "Tributos a Recuperar",
  "CREDITOS FISCAIS": "Tributos a Recuperar",

  // === OUTROS CRÉDITOS A RECEBER ===
  "Créditos Diversos a Receber": "Outros Créditos a Receber",
  "Outros Créditos a Receber": "Outros Créditos a Receber",
  "Outros Créditos": "Outros Créditos a Receber",
  "OUTROS CREDITOS": "Outros Créditos a Receber",
  "Créditos em Circulação": "Outros Créditos a Receber",

  // === DESPESAS ANT. / ADIANTAMENTOS - ATIVO ===
  "Adiantamentos Concedidos": "Despesas Ant. / Adiantamentos - Ativo",
  "ADIANTAMENTOS CONCEDIDOS": "Despesas Ant. / Adiantamentos - Ativo",
  "Despesas Antecipadas": "Despesas Ant. / Adiantamentos - Ativo",
  "DESPESAS ANTECIPADAS": "Despesas Ant. / Adiantamentos - Ativo",
  "Adiantamentos a Terceiros": "Despesas Ant. / Adiantamentos - Ativo",
  "Adiantamentos a Empregados": "Despesas Ant. / Adiantamentos - Ativo",
  "Adiantamentos E Empréstimos": "Despesas Ant. / Adiantamentos - Ativo",
  "Adiantamentos": "Despesas Ant. / Adiantamentos - Ativo",
  "Adiantamento De Salário": "Despesas Ant. / Adiantamentos - Ativo",
  "Adiantamento De Férias": "Despesas Ant. / Adiantamentos - Ativo",
  "Adiantamentos A Fornecedores": "Despesas Ant. / Adiantamentos - Ativo",
  "ADIANTAMENTOS A FORNECEDORES": "Despesas Ant. / Adiantamentos - Ativo",
  "Adiantamento A Fornecedores": "Despesas Ant. / Adiantamentos - Ativo",
  "ADIANTAMENTO A FUNCIONARIOS": "Despesas Ant. / Adiantamentos - Ativo",
  "ADIANTAMENTO DE SALARIOS": "Despesas Ant. / Adiantamentos - Ativo",
  "DESPESAS DO EXERCICIO SEGUINTE": "Despesas Ant. / Adiantamentos - Ativo",
  "SEGUROS A APROPRIAR": "Despesas Ant. / Adiantamentos - Ativo",

  // === OUTROS ATIVOS CIRCULANTES ===
  "Bens e Valores em Circulação": "Outros Ativos Circulantes",
  "Produtos em Transito": "Outros Ativos Circulantes",
  "PRODUTOS EM TRANSITO": "Outros Ativos Circulantes",
  "Produtos em Trânsito": "Outros Ativos Circulantes",
  "Despesas do Exercicio Seguinte": "Outros Ativos Circulantes",
  "CONTAS TRANSITÓRIAS": "Outros Ativos Circulantes",

  // === ATIVO NÃO CIRCULANTE ===
  "Não Circulante": "Ativo Não Circulante",
  "NAO CIRCULANTE": "Ativo Não Circulante",
  "Ativo Não Circulante Total": "Ativo Não Circulante",
  "Total do Ativo Não Circulante": "Ativo Não Circulante",
  "ATIVO NÃO CIRCULANTE": "Ativo Não Circulante",
  "ATIVO NÃO - CIRCULANTE": "Ativo Não Circulante",
  "ATIVO NAO CIRCULANTE": "Ativo Não Circulante",
  "Ativo Permanente": "Ativo Não Circulante",
  "TOTAL DO ATIVO NÃO CIRCULANTE": "Ativo Não Circulante",
  "TOTAL DO ATIVO NAO CIRCULANTE": "Ativo Não Circulante",

  // === REALIZÁVEL A LONGO PRAZO ===
  "Ativo Realizável a Longo Prazo": "Realizável a Longo Prazo",
  "Ativo Realizavel a Longo Prazo": "Realizável a Longo Prazo",
  "Créditos Realizáveis a Longo Prazo": "Realizável a Longo Prazo",
  "Contas a Receber de Longo Prazo": "Realizável a Longo Prazo",
  "Depósitos Realizáveis a Longo Prazo": "Realizável a Longo Prazo",
  "Depósitos Judiciais de Longo Prazo": "Realizável a Longo Prazo",
  "Depósitos para Garantia de Longo Prazo": "Realizável a Longo Prazo",
  "DEPOSITOS JUDICIAIS": "Realizável a Longo Prazo",

  // === INVESTIMENTOS ===
  "Outros Investimentos": "Investimentos",
  "INVESTIMENTOS": "Investimentos",
  "OUTROS INVESTIMENTOS": "Investimentos",
  "Participação Em Outras Empresas": "Investimentos",
  "PARTICIPAÇÃO EM OUTRAS EMPRESAS": "Investimentos",

  // === IMOBILIZADO ===
  "Ativo Imobilizado": "Imobilizado",
  "IMOBILIZADO": "Imobilizado",
  "Propriedade para Investimento": "Imobilizado",
  "Bens Imóveis": "Imobilizado",
  "Edifícios e Terrenos": "Imobilizado",
  "Bens Móveis": "Imobilizado",
  "Máquinas e Equipamentos": "Imobilizado",
  "MAQUINAS E EQUIPAMENTOS": "Imobilizado",
  "Veículos": "Imobilizado",
  "VEICULOS": "Imobilizado",
  "Computadores e Perifericos": "Imobilizado",
  "Instalacoes": "Imobilizado",
  "Maquinas e Equipamentos": "Imobilizado",
  "Moveis e Utensilios": "Imobilizado",
  "MOVEIS E UTENSILIOS": "Imobilizado",
  "Instalaçoes": "Imobilizado",
  "ATIVO FIXO": "Imobilizado",
  "BENS DO IMOBILIZADO": "Imobilizado",
  "BENS E DIREITOS EM USO": "Imobilizado",
  "EDIFICAÇÕES": "Imobilizado",
  "TERRENOS": "Imobilizado",

  // === INTANGÍVEL ===
  "Bens e Direitos em Uso": "Intangível",
  "Projetos e Softwares": "Intangível",
  "Softwares e Licenças": "Intangível",
  "Marcas e Patentes": "Intangível",
  "Intangivel": "Intangível",
  "INTANGIVEL": "Intangível",
  "Ativo Intangível": "Intangível",
  "Ativos Intangiveis": "Intangível",
  "ATIVOS INTANGIVEIS": "Intangível",

  // === BENS A ALIENAR ===
  "Ativos Mantidos para Venda": "Bens a Alienar",

  // === ATIVO DIFERIDO ===
  "Diferido": "Ativo Diferido",

  // === (-) DEPRECIAÇÕES (maps to Imobilizado as a negative) ===
  "(-) Amortização Acumulada": "Imobilizado",
  "(-) Depreciações/Amortizações Acumuladadas": "Imobilizado",
  "Deprec. S/ Comput. Perifericos": "Imobilizado",
  "Deprec. S/ Instalacoes": "Imobilizado",
  "Deprec. S/ Maquinas E Equiptos": "Imobilizado",
  "Deprec. S/ Moveis E Utensilios": "Imobilizado",
  "Depreciacao Acumulada": "Imobilizado",
  "DEPRECIACAO ACUMULADA": "Imobilizado",
  "(-) Depreciaçoes Acumuladas": "Imobilizado",
  "(-) Computadores E Perifericos": "Imobilizado",
  "(-) Moveis E Utensilios": "Imobilizado",
  "(-) Dep. Acum. Instalaçoes": "Imobilizado",
  "(-) DEPRECIAÇÃO ACUMULADA": "Imobilizado",

  // === PASSIVO TOTAL ===
  "Total do Passivo": "Passivo Total",
  "Total Geral do Passivo": "Passivo Total",
  "PASSIVO": "Passivo Total",
  "P A S S I V O": "Passivo Total",
  "PASSIVO TOTAL": "Passivo Total",
  "TOTAL DO PASSIVO": "Passivo Total",
  "Total Passivo": "Passivo Total",
  "SOMA DO PASSIVO": "Passivo Total",
  "TOTAL PASSIVO E PATRIMÔNIO LÍQUIDO": "Passivo Total",
  "TOTAL PASSIVO E PATRIMONIO LIQUIDO": "Passivo Total",

  // === PASSIVO CIRCULANTE ===
  "Passivo Circulante Total": "Passivo Circulante",
  "Total do Passivo Circulante": "Passivo Circulante",
  "PASSIVO CIRCULANTE": "Passivo Circulante",
  "TOTAL DO PASSIVO CIRCULANTE": "Passivo Circulante",
  "TOTAL PASSIVO CIRCULANTE": "Passivo Circulante",

  // === FORNECEDORES ===
  "Contas a Pagar a Fornecedores": "Fornecedores",
  "Contas A Pagar": "Fornecedores",
  "CONTAS A PAGAR": "Fornecedores",
  "Obrigações a Pagar": "Fornecedores",
  "Fornecedores Nacionais": "Fornecedores",
  "FORNECEDORES": "Fornecedores",
  "FORNECEDORES A PAGAR": "Fornecedores",
  "DUPLICATAS A PAGAR": "Fornecedores",

  // === OBRIGAÇÕES TRABALHISTAS ===
  "Pessoal a Pagar": "Obrigações Trabalhistas",
  "Salários e Encargos a Pagar": "Obrigações Trabalhistas",
  "Ferias A Pagar": "Obrigações Trabalhistas",
  "Obrigacoes Trabalhistas": "Obrigações Trabalhistas",
  "Salarios E Ordenados A Pagar": "Obrigações Trabalhistas",
  "Provisão P/Despesas C/ Pessoal": "Obrigações Trabalhistas",
  "PROVISÃO P/DESPESAS C/ PESSOAL": "Obrigações Trabalhistas",
  "Provisões": "Obrigações Trabalhistas",
  "PROVISÕES": "Obrigações Trabalhistas",
  "Férias": "Obrigações Trabalhistas",
  "Provisão para Férias": "Obrigações Trabalhistas",
  "PROVISAO FERIAS": "Obrigações Trabalhistas",
  "PROVISÃO DE FÉRIAS": "Obrigações Trabalhistas",
  "Pensao Alimenticia A Pagar": "Obrigações Trabalhistas",
  "Pessoal / Encargos": "Obrigações Trabalhistas",
  "PESSOAL / ENCARGOS": "Obrigações Trabalhistas",
  "Pensão Alimentícia": "Obrigações Trabalhistas",
  "Licença-Prêmio": "Obrigações Trabalhistas",
  "Plano de Previdência Complementar": "Obrigações Trabalhistas",
  "Provisões para Previdência": "Obrigações Trabalhistas",
  "Plano de Previdência e Assist. Médica": "Obrigações Trabalhistas",
  "Benefícios a Empregados": "Obrigações Trabalhistas",
  "Provisões Trabalhistas e Cíveis": "Obrigações Trabalhistas",
  "Provisões para Contingências": "Obrigações Trabalhistas",
  "Obrigações Trabalhistas": "Obrigações Trabalhistas",
  "Salários A Pagar": "Obrigações Trabalhistas",
  "SALÁRIOS A PAGAR": "Obrigações Trabalhistas",
  "Pro Labore A Pagar": "Obrigações Trabalhistas",
  "Retençoes Trabalhistas": "Obrigações Trabalhistas",
  "Irrf Retido S/ Folha A Recolher": "Obrigações Trabalhistas",
  "Provisões Trabalhistas": "Obrigações Trabalhistas",
  "Provisão De Ferias": "Obrigações Trabalhistas",
  "Provisão De Inss S/ Ferias": "Obrigações Trabalhistas",
  "Provisão Fgts S/ Ferias": "Obrigações Trabalhistas",
  "Encargos Sociais": "Obrigações Trabalhistas",
  "INSS A RECOLHER": "Obrigações Trabalhistas",
  "FGTS A RECOLHER": "Obrigações Trabalhistas",
  "PROVISAO 13o SALARIO": "Obrigações Trabalhistas",
  "PROVISÃO 13º SALÁRIO": "Obrigações Trabalhistas",
  "13o SALARIO A PAGAR": "Obrigações Trabalhistas",
  "ENCARGOS SOCIAIS A PAGAR": "Obrigações Trabalhistas",

  // === OBRIGAÇÕES TRIBUTÁRIAS ===
  "Impostos Parcelados a Longo Prazo": "Obrigações Tributárias",
  "ISS": "Obrigações Tributárias",
  "Tributos e Encargos Sociais": "Obrigações Tributárias",
  "Impostos e Contribuições a Recolher": "Obrigações Tributárias",
  "Obrigações Sociais e Tributárias": "Obrigações Tributárias",
  "Cofins A Pagar": "Obrigações Tributárias",
  "Csll A Pagar": "Obrigações Tributárias",
  "Encargos Sociais A Pagar": "Obrigações Tributárias",
  "Impostos E Contrib. S/ Lucro": "Obrigações Tributárias",
  "Impostos E Contrib. S/ Receita": "Obrigações Tributárias",
  "Inss A Recolher": "Obrigações Tributárias",
  "Irpj A Pagar": "Obrigações Tributárias",
  "Irrf A Pagar": "Obrigações Tributárias",
  "Iss A Pagar": "Obrigações Tributárias",
  "Obrigacoes Tributarias": "Obrigações Tributárias",
  "OBRIGACOES TRIBUTARIAS": "Obrigações Tributárias",
  "Parcelamento De Icms": "Obrigações Tributárias",
  "PARCELAMENTO DE ICMS": "Obrigações Tributárias",
  "Provisão para IRPJ": "Obrigações Tributárias",
  "Provisão para CSLL": "Obrigações Tributárias",
  "Fgts A Recolher": "Obrigações Tributárias",
  "Pis A Pagar": "Obrigações Tributárias",
  "Tributos A Recolher": "Obrigações Tributárias",
  "TRIBUTOS A RECOLHER": "Obrigações Tributárias",
  "Obrigações Fiscais": "Obrigações Tributárias",
  "OBRIGAÇÕES FISCAIS": "Obrigações Tributárias",
  "Impostos, Taxas, Contribuições": "Obrigações Tributárias",
  "Pis A Recolher": "Obrigações Tributárias",
  "Cofins A Recolher": "Obrigações Tributárias",
  "Iss A Recolher": "Obrigações Tributárias",
  "Retenções Fiscais": "Obrigações Tributárias",
  "Iss Retido A Recolher": "Obrigações Tributárias",
  "Ir Retido/Recolher": "Obrigações Tributárias",
  "Ret Pis/Cofins/Csll A Rec": "Obrigações Tributárias",
  "ICMS a Recolher": "Obrigações Tributárias",
  "ISS a Recolher": "Obrigações Tributárias",
  "SIMPLES NACIONAL A RECOLHER": "Obrigações Tributárias",
  "IMPOSTOS A PAGAR": "Obrigações Tributárias",

  // === EMPRÉSTIMOS E FINANCIAMENTOS - CURTO PRAZO ===
  "Emprestimos a Terceiros": "Empréstimos e Financiamentos - Curto Prazo",
  "Emprestimos Bancarios": "Empréstimos e Financiamentos - Curto Prazo",
  "EMPRESTIMOS BANCARIOS": "Empréstimos e Financiamentos - Curto Prazo",
  "Emprestimos de Terceiros": "Empréstimos e Financiamentos - Curto Prazo",
  "EMPRESTIMOS DE TERCEIROS": "Empréstimos e Financiamentos - Curto Prazo",
  "Emprestimos e Financiamentos": "Empréstimos e Financiamentos - Curto Prazo",
  "EMPRESTIMOS E FINANCIAMENTOS": "Empréstimos e Financiamentos - Curto Prazo",
  "Limite de Saque c/ Vinc. Pgto.": "Empréstimos e Financiamentos - Curto Prazo",
  "Empréstimos": "Empréstimos e Financiamentos - Curto Prazo",
  "Emprestimos Bndes": "Empréstimos e Financiamentos - Curto Prazo",
  "Pronampe - Cp": "Empréstimos e Financiamentos - Curto Prazo",
  "(-) Juros Pronampe - Cp": "Empréstimos e Financiamentos - Curto Prazo",
  "Emprestimos": "Empréstimos e Financiamentos - Curto Prazo",
  "Emprestimos Lp": "Empréstimos e Financiamentos - Curto Prazo",
  "Pronampe - Lp": "Empréstimos e Financiamentos - Curto Prazo",
  "(-) Juros Pronampe - Lp": "Empréstimos e Financiamentos - Curto Prazo",
  "Financiamentos": "Empréstimos e Financiamentos - Curto Prazo",
  "Empréstimos Bancários": "Empréstimos e Financiamentos - Curto Prazo",

  // === PASSIVOS COM PARTES RELACIONADAS - CURTO PRAZO ===
  "Passivos com Partes Relacionadas": "Passivos com Partes Relacionadas - Curto Prazo",

  // === DIVIDENDOS E JCP A PAGAR ===
  "Dividendos e JCP a Pagar": "Dividendos e JCP a Pagar",

  // === DESPESAS ANT. / ADIANTAMENTOS - PASSIVO ===
  "Adiantamento Recebido": "Despesas Ant. / Adiantamentos - Passivo",
  "ADIANTAMENTO RECEBIDO": "Despesas Ant. / Adiantamentos - Passivo",
  "Adiantamento De Clientes": "Despesas Ant. / Adiantamentos - Passivo",

  // === OUTROS PASSIVOS CIRCULANTES ===
  "Outras Obrigações": "Outros Passivos Circulantes",
  "OUTRAS OBRIGAÇÕES": "Outros Passivos Circulantes",
  "Outras Contas a Pagar": "Outros Passivos Circulantes",
  "Obrigações em Circulação": "Outros Passivos Circulantes",
  "Valores Pendentes a Curto Prazo": "Outros Passivos Circulantes",

  // === PASSIVO NÃO CIRCULANTE ===
  "Passivo Exigivel A Longo Prazo": "Passivo Não Circulante",
  "PASSIVO EXIGIVEL A LONGO PRAZO": "Passivo Não Circulante",
  "NÃO CIRCULANTE": "Passivo Não Circulante",
  "Passivo Não Circulante Total": "Passivo Não Circulante",
  "Total do Passivo Não Circulante": "Passivo Não Circulante",
  "PASSIVO NÃO CIRCULANTE": "Passivo Não Circulante",
  "PASSIVO NAO CIRCULANTE": "Passivo Não Circulante",
  "TOTAL DO PASSIVO NÃO CIRCULANTE": "Passivo Não Circulante",
  "TOTAL DO PASSIVO NAO CIRCULANTE": "Passivo Não Circulante",
  "Exigível a Longo Prazo": "Passivo Não Circulante",

  // === EMPRÉSTIMOS E FINANCIAMENTOS - LONGO PRAZO ===
  "Financiamentos de Longo Prazo": "Empréstimos e Financiamentos - Longo Prazo",
  "Empréstimos de Longo Prazo": "Empréstimos e Financiamentos - Longo Prazo",
  "EMPRESTIMOS BANCARIOS LP": "Empréstimos e Financiamentos - Longo Prazo",
  "FINANCIAMENTOS LP": "Empréstimos e Financiamentos - Longo Prazo",
  "FINANCIAMENTOS A LONGO PRAZO": "Empréstimos e Financiamentos - Longo Prazo",

  // === TRIBUTOS DIFERIDOS - LONGO PRAZO ===
  "Tributos Diferidos": "Tributos Diferidos - Longo Prazo",

  // === ADIANTAMENTO PARA FUTURO AUMENTO CAPITAL - LP ===
  "Adiantamento para Futuro Aumento Capital": "Adiantamento para Futuro Aumento Capital - Longo Prazo",

  // === PARTICIPAÇÃO NOS LUCROS OU RESULTADOS ===
  "PLR a Pagar": "Participação nos Lucros ou Resultados",

  // === DIVIDENDOS E JUROS SOBRE O CAPITAL PRÓPRIO ===
  "Dividendos a Pagar": "Dividendos e Juros sobre o Capital Próprio",

  // === PATRIMÔNIO LÍQUIDO ===
  "Total do Patrimônio Líquido": "Patrimônio Líquido",
  "Patrimonio Liquido": "Patrimônio Líquido",
  "PATRIMONIO LIQUIDO": "Patrimônio Líquido",
  "PATRIMÔNIO LÍQUIDO": "Patrimônio Líquido",
  "Patrimonio Líquido": "Patrimônio Líquido",
  "PL": "Patrimônio Líquido",
  "TOTAL DO PATRIMÔNIO LÍQUIDO": "Patrimônio Líquido",
  "TOTAL DO PATRIMONIO LIQUIDO": "Patrimônio Líquido",
  "TOTAL PATRIMÔNIO LÍQUIDO": "Patrimônio Líquido",

  // === CAPITAL SOCIAL ===
  "Capital": "Capital Social",
  "Capital Social Subscrito": "Capital Social",
  "CAPITAL SOCIAL": "Capital Social",
  "Capital Realizado": "Capital Social",
  "Capital Integralizado": "Capital Social",
  "Capital Registrado": "Capital Social",
  "Capital Social Integralizado": "Capital Social",
  "Capital Social Realizado": "Capital Social",
  "CAPITAL INTEGRALIZADO": "Capital Social",
  "CAPITAL SUBSCRITO E INTEGRALIZADO": "Capital Social",

  // === RESERVAS DE CAPITAL ===
  "RESERVAS DE CAPITAL": "Reservas de Capital",

  // === RESERVAS DE LUCROS ===
  "Reservas": "Reservas de Lucros",
  "RESERVAS": "Reservas de Lucros",
  "Reserva Legal": "Reservas de Lucros",
  "RESERVA LEGAL": "Reservas de Lucros",
  "Reserva de Lucros": "Reservas de Lucros",
  "Reserva de Capital": "Reservas de Capital",
  "Reservas Estatutárias": "Reservas de Lucros",
  "RESERVAS ESTATUTÁRIAS": "Reservas de Lucros",
  "Reserva de Retenção do Lucro": "Reservas de Lucros",
  "Reserva Especial de Dividendos": "Reservas de Lucros",

  // === LUCROS/PREJUÍZOS ACUMULADOS ===
  "Lucros Ou Prejuizos": "Lucros/Prejuízos Acumulados",
  "Lucros Ou Prejuizos Acumulados": "Lucros/Prejuízos Acumulados",
  "LUCROS OU PREJUIZOS ACUMULADOS": "Lucros/Prejuízos Acumulados",
  "Resultados Acumulados": "Lucros/Prejuízos Acumulados",
  "Lucros Acumulados": "Lucros/Prejuízos Acumulados",
  "LUCROS ACUMULADOS": "Lucros/Prejuízos Acumulados",
  "Prejuízos Acumulados": "Lucros/Prejuízos Acumulados",
  "PREJUIZOS ACUMULADOS": "Lucros/Prejuízos Acumulados",
  "Resultado Acumulado": "Lucros/Prejuízos Acumulados",
  "RESULTADO ACUMULADO": "Lucros/Prejuízos Acumulados",

  // === RESULTADO DO EXERCÍCIO ===
  "Resultado Do Exercicio": "Resultado do Exercício",
  "RESULTADO DO EXERCICIO": "Resultado do Exercício",
  "RESULTADO DO EXERCÍCIO": "Resultado do Exercício",
  "LUCRO DO EXERCICIO": "Resultado do Exercício",

  // ===== DRE ALIASES =====
  "Receita Operacional Bruta": "Receita Bruta",
  "Receita Bruta": "Receita Bruta",
  "RECEITA BRUTA DE VENDAS E SERVIÇOS": "Receita Bruta",
  "RECEITA BRUTA DE VENDAS E SERVICOS": "Receita Bruta",
  "Faturamento Bruto": "Receita Bruta",
  "VENDA DE MERCADORIAS E PRODUTOS": "Receita Bruta",
  "RECEITA OPERACIONAL BRUTA": "Receita Bruta",
  "RECEITA BRUTA DE VENDAS": "Receita Bruta",
  "RECEITA BRUTA DE SERVIÇOS": "Receita Bruta",
  "VENDAS DE MERCADORIAS": "Receita Bruta",
  "VENDAS DE PRODUTOS": "Receita Bruta",
  "PRESTAÇÃO DE SERVIÇOS": "Receita Bruta",
  "FATURAMENTO": "Receita Bruta",
  "RECEITA DE VENDAS": "Receita Bruta",
  // Note: "RECEITAS OPERACIONAIS" is NOT Receita Bruta — it's the total after
  // deductions. But in many DREs it's used as the top-level revenue line.
  // Map to Receita Bruta only when no separate Receita Bruta line exists.
  "RECEITAS OPERACIONAIS": "Receita Bruta",

  "(-) Deduções": "Deduções da Receita Bruta",
  "Deduções": "Deduções da Receita Bruta",
  "DEDUCOES DAS VENDAS": "Deduções da Receita Bruta",
  "DEDUÇÕES DAS VENDAS": "Deduções da Receita Bruta",
  "Impostos sobre Vendas": "Deduções da Receita Bruta",
  "ABATIMENTOS E DEVOLUÇÕES SOBRE VENDAS": "Deduções da Receita Bruta",
  "DEDUÇÕES DA RECEITA": "Deduções da Receita Bruta",
  "IMPOSTOS SOBRE VENDAS": "Deduções da Receita Bruta",
  "TRIBUTOS SOBRE VENDAS": "Deduções da Receita Bruta",
  "IMPOSTOS INCIDENTES SOBRE VENDAS": "Deduções da Receita Bruta",
  "DEVOLUÇÕES DE VENDAS": "Deduções da Receita Bruta",
  "CANCELAMENTOS": "Deduções da Receita Bruta",

  "Receita Operacional Líquida": "Receita Líquida",
  "Receita Líquida de Vendas": "Receita Líquida",
  "RECEITA LIQUIDA": "Receita Líquida",
  "RECEITA OPERACIONAL LÍQUIDA": "Receita Líquida",
  "RECEITA OPERACIONAL LIQUIDA": "Receita Líquida",

  "CMV": "Custo Operacional",
  "CPV": "Custo Operacional",
  "Custo das Mercadorias Vendidas": "Custo Operacional",
  "CUSTO DAS MERCADORIAS VENDIDAS": "Custo Operacional",
  "Custo dos Produtos Vendidos": "Custo Operacional",
  "CUSTO PRODUTOS VENDIDOS": "Custo Operacional",
  "Custo dos Serviços Prestados": "Custo Operacional",
  "CUSTO DOS SERVIÇOS PRESTADOS": "Custo Operacional",
  "CUSTOS OPERACIONAIS": "Custo Operacional",
  "CUSTO DAS VENDAS": "Custo Operacional",
  "CMV/CPV/CSP": "Custo Operacional",

  "Lucro Bruto": "Lucro Bruto",
  "Resultado Operacional Bruto": "Lucro Bruto",
  "RESULTADO BRUTO": "Lucro Bruto",
  "LUCRO BRUTO": "Lucro Bruto",

  "Despesas Administrativas": "Despesas Gerais e Administrativas",
  "Despesas Gerais": "Despesas Gerais e Administrativas",
  "DESPESAS GERAIS": "Despesas Gerais e Administrativas",
  "DESPESAS C/ PESSOAL": "Despesas Gerais e Administrativas",
  "DESPESAS ADMINISTRATIVAS": "Despesas Gerais e Administrativas",
  "DESPESAS GERAIS E ADMINISTRATIVAS": "Despesas Gerais e Administrativas",
  "DESPESAS COM PESSOAL": "Despesas Gerais e Administrativas",

  "Despesas com Vendas": "Despesas com Vendas",
  "Despesas Comerciais": "Despesas com Vendas",
  "DESPESAS COMERCIAIS": "Despesas com Vendas",
  "DESPESAS COM TRANSPORTES": "Despesas com Vendas",
  "DESPESAS DE VENDAS": "Despesas com Vendas",

  "Lucro Operacional": "EBIT",
  "EBIT": "EBIT",
  "Resultado Operacional Líquido": "EBIT",

  "OUTRAS RECEITAS OPERACIONAIS": "Outras Receitas Operacionais",
  "OUTRAS RECEITAS": "Outras Receitas Operacionais",
  "OUTRAS DESPESAS OPERACIONAIS": "Outras Despesas Operacionais",
  "IMPOSTOS E TAXAS": "Outras Despesas Operacionais",

  "Equivalência Patrimonial": "Equivalência Patrimonial",
  "Resultado Financeiro Líquido": "Resultado Financeiro",
  "RECEITAS FINANCEIRAS": "Receitas Financeiras",
  "DESPESAS FINANCEIRAS": "Despesas Financeiras",

  "LAIR": "Resultado Antes do IR e CSLL",
  "Lucro Antes do IR": "Resultado Antes do IR e CSLL",
  "Resultado Antes dos Tributos": "Resultado Antes do IR e CSLL",
  "RESULTADO ANTES DO IRPJ E CSLL": "Resultado Antes do IR e CSLL",
  "LUCRO ANTES DOS TRIBUTOS": "Resultado Antes do IR e CSLL",

  "IR e CSLL": "IR e CSLL",
  "Imposto de Renda": "IR e CSLL",
  "IRPJ e CSLL": "IR e CSLL",
  "PROVISÃO PARA IRPJ": "IR e CSLL",
  "IMPOSTOS SOBRE O LUCRO": "IR e CSLL",

  "Lucro Líquido": "Lucro Líquido",
  "Prejuízo do Período": "Lucro Líquido",
  "Resultado Líquido": "Lucro Líquido",
  "RESULTADO LIQUIDO DO EXERCICIO": "Lucro Líquido",
  "Lucro/Prejuízo": "Lucro Líquido",
  "Lucro do Exercício": "Lucro Líquido",
  "Resultado do Exercício": "Lucro Líquido",
  "LUCRO LIQUIDO": "Lucro Líquido",
  "LUCRO LÍQUIDO": "Lucro Líquido",
  "RESULTADO DO PERIODO": "Lucro Líquido",
  "RESULTADO DO PERÍODO": "Lucro Líquido",
  "Lucro/Prejuízo do Exercício": "Lucro Líquido",

  "DESPESAS NÃO OPERACIONAIS": "Outras Despesas Não Operacionais",

  "CUSTO PRODUTOS MERCADORIAS E SERVIÇOS": "Custo Operacional",
  "CUSTO DAS MERCADORIAS REVENDIDAS": "Custo Operacional",

  "DEDUÇÕES DA RECEITA BRUTA": "Deduções da Receita Bruta",

  "PROV P IMPOSTO DE RENDA E CONTRIBUIÇÃO SOCIAL": "IR e CSLL",

  // ── Linhas novas do DRE padrão gerencial (Modelo_DRE.xlsx) ──
  "Impostos s/ Faturamento": "Impostos s/ Faturamento",
  "Impostos sobre Faturamento": "Impostos s/ Faturamento",
  "IMPOSTOS S/FATURAMENTO": "Impostos s/ Faturamento",
  "IMPOSTOS S/ FATURAMENTO": "Impostos s/ Faturamento",
  "Simples Nacional": "Impostos s/ Faturamento",
  "SIMPLES NACIONAL": "Impostos s/ Faturamento",

  "Despesas com Marketing": "Despesas com Marketing",
  "Despesas de Marketing": "Despesas com Marketing",
  "DESPESAS COM MARKETING": "Despesas com Marketing",
  "Marketing": "Despesas com Marketing",
  "Publicidade e Propaganda": "Despesas com Marketing",
  "PUBLICIDADE E PROPAGANDA": "Despesas com Marketing",

  "Despesas com P&D": "Despesas com P&D",
  "Despesas com Pesquisa e Desenvolvimento": "Despesas com P&D",
  "DESPESAS COM P&D": "Despesas com P&D",
  "Pesquisa e Desenvolvimento": "Despesas com P&D",
  "PESQUISA E DESENVOLVIMENTO": "Despesas com P&D",
  "P&D": "Despesas com P&D",

  "EBITDA": "EBITDA",
  "LAJIDA": "EBITDA",
  "Geração de Caixa Operacional": "EBITDA",

  "Depreciação e Amortização": "Depreciação e Amortização",
  "Depreciação": "Depreciação e Amortização",
  "DEPRECIAÇÃO": "Depreciação e Amortização",
  "Amortização": "Depreciação e Amortização",
  "AMORTIZAÇÃO": "Depreciação e Amortização",
  "Depreciações e Amortizações": "Depreciação e Amortização",
  "(-) Depreciação e Amortização": "Depreciação e Amortização",

  "Resultado da Equivalência Patrimonial": "Equivalência Patrimonial",
  "EQUIVALÊNCIA PATRIMONIAL": "Equivalência Patrimonial",

  "Outras Receitas Não Operacionais": "Outras Receitas Não Operacionais",
  "OUTRAS RECEITAS NÃO OPERACIONAIS": "Outras Receitas Não Operacionais",
  "Receitas Não Operacionais": "Outras Receitas Não Operacionais",
  "Outras Despesas Não Operacionais": "Outras Despesas Não Operacionais",
  "OUTRAS DESPESAS NÃO OPERACIONAIS": "Outras Despesas Não Operacionais",
  "Despesas Não Operacionais": "Outras Despesas Não Operacionais",
};
